### ISSUE TITLE
Rewrite recipe for GSTools 1.3

### ISSUE THREAD

**Issue by MuellerSeb** [conda-forge/gstools-feedstock#7]
Since GSTools 1.3 will control the parallel build with an environment variable, we need to take care of this when it is released
- https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#use-environment-variables

Also we need to update the build command, to not create build dependencies now defined in pyproject.toml.
- https://pip.pypa.io/en/stable/reference/pip/#pep-517-and-518-support
- https://pip.pypa.io/en/stable/reference/pip_install/#cmdoption-no-build-isolation

Recipe could be updated as follows:
```yaml
build:
  number: 0
  script_env:
   - GSTOOLS_BUILD_PARALLEL=1
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
```
